<?php

use Illuminate\Database\Seeder;

class RestaurantsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        \Illuminate\Support\Facades\DB::statement('SET FOREIGN_KEY_CHECKS = 0');
        \Illuminate\Support\Facades\DB::table('restaurants')->truncate();
        \Illuminate\Support\Facades\DB::table('restaurants')->insert([
            [
                'categoryID' => 1,
                'name' => 'Salmonoid - Món Âu - Cao Bá Quát',
                'avartar' => 'salmonoid-mon-au-cao-180821141936.jpg',
                'addressID' => 1,
                'addressDetail' => '32C Cao Bá Quát',
                'phone' => '0984480116',
                'openTime' => '08:30',
                'closeTime' => '21:00',
                'shortDescription' => 'Sang trọng, cặp đôi, gia đình',
                'description' => 'Quán nằm nhỏ nhắn xinh xắn trên con phố cao bá quát, lối nhỏ từ ngoài cổng đi vào quán có hàng rào cây xanh nhìn rất đẹp và mát mắt, bạn có thể selfie dc khá nhiều ảnh đẹp ở chỗ đó :))',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryID' => 1,
                'name' => 'Tim Ho Wan - Dimsum Hồng Kông - Lotte Hotel Hanoi',
                'avartar' => 'foody-mobile-tim-jpg-652-636129899200456707.jpg',
                'addressID' => 2,
                'addressDetail' => 'Tầng 36, Lotte Center, 54 Liễu Giai',
                'phone' => '0984480116',
                'openTime' => '08:30',
                'closeTime' => '21:00',
                'shortDescription' => 'Sang trọng, món trung hoa, cặp đôi, gia đình nhỏ',
                'description' => 'Vị thì rất đẹp, ngay trong toà khách sạn, gửi xe xong đi thẳng vào, bấm thang lên 36, rẽ phải, luôn có nhân viên lễ tân đứng cửa để đón khách và xếp bàn.',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryID' => 1,
                'name' => 'Top Floor Rue Des Seaux Restaurant - Hàng Thùng',
                'avartar' => 'foody-top-floor-rue-des-seaux-restaurant-477-636358922864083943.jpg',
                'addressID' => 3,
                'addressDetail' => '21 Hàng Thùng',
                'phone' => '0984480116',
                'openTime' => '08:30',
                'closeTime' => '21:00',
                'shortDescription' => 'Sang trọng, nhà hàng-quốc tế-cặp đôi',
                'description' => 'Nhà hàng có view vào buổi tối khá đẹp, hướng Hồ Gươm hay cầu Chương Dương đều có cái đẹp riêng. Nhân viên phục vụ cũng khá chuyên nghiệp, lịch sự và vui vẻ.',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryID' => 1,
                'name' => 'Tunglok Heen - Ẩm Thực Trung Hoa - Almaz Vinhomes Riverside',
                'avartar' => 'foody-top-floor-rue-des-seaux-restaurant-477-636358922864083943.jpg',
                'addressID' => 4,
                'addressDetail' => 'Almaz, Vinhomes Riverside,  Quận Long Biên',
                'phone' => '0984480116',
                'openTime' => '08:30',
                'closeTime' => '21:00',
                'shortDescription' => 'Sang trọng, nhà hàng - món Trung Hoa - nhóm hội',
                'description' => 'Nhà hàng siêu hoành tráng, đẹp miễn chê. Nhìn bên ngoài như Tử Cấm Thàng, bên trong không gian rộng rãi tráng lệ kiểu hoàng cung.',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryID' => 1,
                'name' => 'Top Of Hanoi - Lotte Hotels & Resorts Hanoi',
                'avartar' => 'foody-mobile-top1-jpg-973-635742117477155490.jpg',
                'addressID' => 5,
                'addressDetail' => 'Tầng 67, Lotte Center, 54 Liễu Giai',
                'phone' => '0984480116',
                'openTime' => '08:30',
                'closeTime' => '21:00',
                'shortDescription' => 'Sang trọng, nhà hàng - món Việt, quốc tế - cặp đôi',
                'description' => 'Vị trí: nằm trên tầng 67 của khách sạn Lotte. Dạng rooftop bar.
                                  Không gian: đẹp, cực đẹp. Sang trọng và lịch sự. 
                                  Có thể nhìn bao quát thủ đô. Mát mẻ đi khuya thì hơi lạnh,
                                   có nhạc nên không khí quán khá náo nhiệt, nhiều khách du lịch như mình và khách nước ngoài.',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryID' => 1,
                'name' => 'Maison De Tet Decor Cafe - Từ Hoa',
                'avartar' => 'foody-mobile-maison-1-mb-jpg-617-635857130884455566.jpg',
                'addressID' => 6,
                'addressDetail' => '36 Từ Hoa Công Chúa',
                'phone' => '0984480116',
                'openTime' => '08:30',
                'closeTime' => '21:00',
                'shortDescription' => 'Sang trọng, Nhà hàng - Quốc tế - Gia đình',
                'description' => 'Không gian hẹn hò lý tưởng cho các cặp đôi mọi người nhen. Quán có khá nhiều không gian ngồi cho mng lựa chọn từ sân vườn, trong nhà, ban công, khu bàn ăn như homestay, quán yên tĩnh lắm nha',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryID' => 1,
                'name' => 'El Gaucho Steakhouse - Xuân Diệu',
                'avartar' => 'foody-mobile-maison-1-mb-jpg-617-635857130884455566.jpg',
                'addressID' => 7,
                'addressDetail' => 'Lô G2 Tầng trệt, Tòa nhà Somerset West Point, 2 Tây Hồ',
                'phone' => '0984480116',
                'openTime' => '08:30',
                'closeTime' => '21:00',
                'shortDescription' => 'Sang trọng, Nhà hàng - Argentina',
                'description' => 'Vị trí quán đắc địa, nằm ở ngã ba xuân diệu yên phụ, view gần hồ tây, dễ tìm
                                  Quán bài trí theo kiểu tây, liên tưởng đến các nhà hàng châu mỹ. 
                                  Đặc biệt buổi tối thắp nến, ngồi ăn rất lãng mạn',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryID' => 1,
                'name' => 'Pane e Vino - Ẩm Thực Ý - Nguyễn Khắc Cần',
                'avartar' => 'foody-album8-jpg-571-636294066162913359.jpg',
                'addressID' => 8,
                'addressDetail' => '3 Nguyễn Khắc Cần, P. Tràng Tiền',
                'phone' => '0984480116',
                'openTime' => '08:30',
                'closeTime' => '21:00',
                'shortDescription' => 'Sang trọng, Nhà hàng - Ý - Cặp đôi, Gia đình',
                'description' => 'Nằm đối diện khách sạn L\opera.. khá khuất nhưng có khá lâu năm rồi',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryID' => 1,
                'name' => 'Rico South American Steakhouse',
                'avartar' => 'foody-mobile-rico-jpg-419-636178309399268457.jpg',
                'addressID' => 9,
                'addressDetail' => '56 Trần Quốc Toản',
                'phone' => '0984480116',
                'openTime' => '08:30',
                'closeTime' => '21:00',
                'shortDescription' => 'Sang trọng, Nhà hàng - Món Việt - Gia đình, Nhóm hội',
                'description' => 'Quán bài trí theo phong cách Nam Mỹ rất lịch sự, ấm cúng.',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryID' => 1,
                'name' => 'La Salsa - Món Âu - Xuân Diệu',
                'avartar' => 'foody-mobile-lasalsa-jpg-399-635768741864567006.jpg',
                'addressID' => 10,
                'addressDetail' => '53 Xuân Diệu',
                'phone' => '0984480116',
                'openTime' => '08:30',
                'closeTime' => '21:00',
                'shortDescription' => 'Sang trọng, Nhà hàng - Pháp, Tây Ban Nha - Cặp đôi, Gia đình',
                'description' => ' Không gian: nhà hàng gồm 2 khu: bánh ngọt ở bên ngoài và nhà hàng ăn ở bên trong. Cả 2 khu đều decor đẹp đơn giản. ',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryID' => 1,
                'name' => 'Da Paolo Westlake - Món Ý',
                'avartar' => 'foody-mobile-paolo-jpg-187-635762636793592761.jpg',
                'addressID' => 11,
                'addressDetail' => '18 Ngõ 50/59/17 Đặng Thai Mai',
                'phone' => '0984480116',
                'openTime' => '08:30',
                'closeTime' => '21:00',
                'shortDescription' => 'Sang trọng, Nhà hàng - Ý - Gia đình, Nhóm hội',
                'description' => ' không gian đẹp. Nhân viên phục vụ nhiệt tình.',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryID' => 1,
                'name' => 'Jacksons Steakhouse Hanoi',
                'avartar' => 'foody-mobile-18dorpx7-jpg-484-636118701698799751.jpg',
                'addressID' => 12,
                'addressDetail' => '23J Hai Bà Trưng',
                'phone' => '0984480116',
                'openTime' => '08:30',
                'closeTime' => '21:00',
                'shortDescription' => 'Sang trọng, Nhà hàng - Mỹ, Úc - Cặp đôi, Giới văn phòng',
                'description' => 'Quán đối diện tràng tiền plaza không gian tuy ko to lắm nhưng khá là đẹp và sang trọng. Giá cả ở mức trung bình.',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryID' => 1,
                'name' => 'Maison Vie - Nhà Hàng Kiểu Pháp',
                'avartar' => 'foody-mobile-maison-jpg-586-636057258224334666.jpg',
                'addressID' => 13,
                'addressDetail' => '28 Tăng Bạt Hổ',
                'phone' => '0984480116',
                'openTime' => '08:30',
                'closeTime' => '21:00',
                'shortDescription' => 'Sang trọng, Nhà hàng - Pháp - Gia đình, Nhóm hội',
                'description' => 'Vị trí: rất dễ tìm khi từ Lò Đúc rẽ vào phố Tăng Bạt Hổ, con phố yên tĩnh và rộng rãi, nhà hàng nằm ngay mặt đường, vô cùng thuận tiện',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryID' => 1,
                'name' => 'Sunset Bar - InterContinental Hanoi Westlake',
                'avartar' => 'foody-mobile-sunset-bar-ha-noi-140513022951.jpg',
                'addressID' => 14,
                'addressDetail' => 'InterContinental Hanoi Westlake, 5 Từ Hoa',
                'phone' => '0984480116',
                'openTime' => '08:30',
                'closeTime' => '21:00',
                'shortDescription' => 'Sang trọng, Bar/Pub - Món Việt - Cặp đôi, Nhóm hội',
                'description' => ' View cực kì đẹp, rộng rãi thoáng mát và thấy bình thản trong tâm hồn. Ban đêm bar được trang hoàng đèn điện nhìn trông đẹp ngất ngây',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryID' => 1,
                'name' => 'Oven Dor Buffet - Sheraton Hanoi Hotel',
                'avartar' => 'foody-oven-d-or-sheraton-ha-noi-635459467185389071.jpg',
                'addressID' => 15,
                'addressDetail' => 'Sheraton Hanoi Hotel, 11 Xuân Diệu',
                'phone' => '0984480116',
                'openTime' => '08:30',
                'closeTime' => '21:00',
                'shortDescription' => 'Sang trọng, Nhà hàng - Món Việt, Quốc tế - Gia đình, Nhóm hội',
                'description' => 'không gian khá là yên tĩnh, trang trí ở đây quá đẹp , đồ ăn ở đây rất chất lượng và rất ngon , có khá nhiều sự lựa chọn ',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryID' => 2,
                'name' => 'Sumo BBQ - Nhà Hàng Thịt Nướng Nhật Bản - Hoàng Quốc Việt',
                'avartar' => 'foody-mobile-sumo-bbq-hn-mb-jpg-960-635706643555146613.jpg',
                'addressID' => 1,
                'addressDetail' => '132 - 134 Hoàng Quốc Việt',
                'phone' => '0984480116',
                'openTime' => '08:30',
                'closeTime' => '21:00',
                'shortDescription' => 'Nhà hàng, Buffet - Món Nhật',
                'description' => 'Buffet ở Sumo BBQ nhiều món, tha hồ lựa chọn, thịt có độ tươi, thấm gia vị, cho món nướng đậm đà, có vị ngon độc đáo. Hơn nữa tthịt được nướng bằng than hoa ngay tại bàn, những lát thịt nóng hổi đậm vị, chín tới, thịt thơm mềm mại, kết hợp cùng nước sốt đặc biệt ăn ngon lắm nhé!',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryID' => 2,
                'name' => 'Buffet Sen - Lý Thái Tổ',
                'avartar' => 'foody-mobile-buffet-sen-ly-thai-to-ha-noi-140225115808.jpg',
                'addressID' => 2,
                'addressDetail' => '60 Lý Thái Tổ',
                'phone' => '0984480116',
                'openTime' => '08:30',
                'closeTime' => '21:00',
                'shortDescription' => 'Buffet, Tiệc cưới/Hội nghị - Quốc tế - Gia đình, Nhóm hội',
                'description' => 'Vị trí đẹp ngay trung tâm hà nội khu phố du lịch bờ hồ. Ko gian sang trọng, chỗ ngồi thoáng',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryID' => 2,
                'name' => 'Chef Dzung - BBQ & Hotpot Buffet',
                'avartar' => 'foody-mobile-3-jpg-414-635767168878236201.jpg',
                'addressID' => 3,
                'addressDetail' => 'Tầng 3, TTTM 71 Nguyễn Chí Thanh, P. Láng Hạ',
                'phone' => '0984480116',
                'openTime' => '08:30',
                'closeTime' => '21:00',
                'shortDescription' => 'Buffet - Món Hàn - Gia đình, Nhóm hội',
                'description' => 'khu trung tâm nguyễn chí thanh, thuận lợi cho anh em hẹn hò',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryID' => 2,
                'name' => 'Isushi Buffet Nhật Bản - Nguyễn Chí Thanh',
                'avartar' => 'foody-sumo-sushibar-130-635573972300702282.jpg',
                'addressID' => 4,
                'addressDetail' => '16 Nguyễn Chí Thanh',
                'phone' => '0984480116',
                'openTime' => '08:30',
                'closeTime' => '21:00',
                'shortDescription' => 'Nhà hàng, Buffet - Món Nhật - Gia đình, Nhóm hộ',
                'description' => 'không gian đẹp, sạch sẽ, sang chảnh, có dịch vụ tổ chức sinh nhật',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryID' => 2,
                'name' => 'Yakimono - Nướng Nhật Bản - Nguyên Hồng',
                'avartar' => 'foody-mobile-ltojw2vf-jpg-411-635796381433088835.jpg',
                'addressID' => 5,
                'addressDetail' => '36 Nguyên Hồng',
                'phone' => '0984480116',
                'openTime' => '08:30',
                'closeTime' => '21:00',
                'shortDescription' => 'Nhà hàng - Món Nhật - Cặp đôi, Gia đình',
                'description' => 'quán nằm đoạn nguyên hồng nhé, nhìn từ bên ngoài đã nhận ra quán luôn rồi a. Bên ngoài quán to đùng, trang trí nổi bật tông màu đỏ luôn nhé. Bên trong ko gian rộng mà khá là thoáng nữa a',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryID' => 2,
                'name' => 'Sứ Buffet - Hải Sản Á & Âu',
                'avartar' => 'foody-mobile-su-buffet-ha-noi.jpg',
                'addressID' => 6,
                'addressDetail' => '64 Nguyễn Du',
                'phone' => '0984480116',
                'openTime' => '08:30',
                'closeTime' => '21:00',
                'shortDescription' => 'Nhà hàng, Buffet - Món Á, Món Âu',
                'description' => 'Giá CN - buổi trưa: 298k/ adult. chưa bao gồm nước
                                  Trẻ em từ 1m-1.39m thì 50% giá người lớn
                                  Trẻ em dưới 1m thì FREE.
                                  Địa chỉ tại 64 Nguyễn Du - đối diện hồ Thiền Quang.',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryID' => 2,
                'name' => 'King BBQ Deli - Vincom Bà Triệu',
                'avartar' => 'foody-mobile-bbq5-jpg-460-635748868933039961.jpg',
                'addressID' => 7,
                'addressDetail' => 'Tầng 5, Vincom Bà Triệu, 191 Bà Triệu',
                'phone' => '0984480116',
                'openTime' => '08:30',
                'closeTime' => '21:00',
                'shortDescription' => 'Nhà hàng - Gia đình, Nhóm hội',
                'description' => 'Nhà hàng king bbq deli này nằm ở trên tầng 5 vincom bà triệu 
                                  Không gian nhà hàng cũng rộng rãi, phục vụ cũng nhanh nhẹn',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryID' => 2,
                'name' => 'Nhà Hàng Hương Sen - Buffet Hải Sản Cao Cấp',
                'avartar' => 'foody-mobile-huong-sen-jpg-886-635841338923288386.jpg',
                'addressID' => 8,
                'addressDetail' => '269 Đỗ Đức Dục, Mễ Trì',
                'phone' => '0984480116',
                'openTime' => '08:30',
                'closeTime' => '21:00',
                'shortDescription' => 'Nhà hàng, Buffet, Tiệc cưới/Hội nghị - Món Việt - Cặp đôi, Gia đình',
                'description' => 'Nhà hàng king bbq deli này nằm ở trên tầng 5 vincom bà triệu 
                                  Không gian nhà hàng cũng rộng rãi, phục vụ cũng nhanh nhẹn',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryID' => 2,
                'name' => 'Seoul Garden - Buffet Lẩu & Nướng Trần Hưng Đạo',
                'avartar' => 'foody-mobile-sg1-jpg-692-635769630631824043.jpg',
                'addressID' => 9,
                'addressDetail' => '33 Trần Hưng Đạo, P. Phan Chu Trinh',
                'phone' => '0984480116',
                'openTime' => '08:30',
                'closeTime' => '21:00',
                'shortDescription' => 'Nhà hàng, Buffet - Món Hàn - Cặp đôi, Gia đình',
                'description' => '*Địa điểm dễ tìm
                                  *Nhân viên phục vụ rất nhiệt tình
                                  * Không gian sang chảnh mát mẻ, đẹp.
                                  *Giá cả hợp lý',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryID' => 2,
                'name' => 'Kowloon - Buffet Dimsum & Lẩu Hồng Kông',
                'avartar' => 'foody-album13307413_16757281293-331-636022985530177326.jpg',
                'addressID' => 10,
                'addressDetail' => '116-B6 Phạm Ngọc Thạch',
                'phone' => '0984480116',
                'openTime' => '08:30',
                'closeTime' => '21:00',
                'shortDescription' => 'Nhà hàng, Buffet - Món Á - Gia đình, Nhóm hội',
                'description' => 'Địa điểm: mặt đường Phạm Ngọc Thạch, dễ tìm.',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryID' => 2,
                'name' => 'Nghiện Lẩu Buffet',
                'avartar' => 'foody-mobile-nghien-jpg-443-636331379645792657.jpg',
                'addressID' => 11,
                'addressDetail' => '2B Ngõ Bà Triệu, Bà Triệu',
                'phone' => '0984480116',
                'openTime' => '08:30',
                'closeTime' => '21:00',
                'shortDescription' => 'Buffet - Món Việt - Gia đình, Nhóm hội',
                'description' => 'Vị trí : ngay ở đầu đường Bà Triệu nhưng khách nên chú ý tránh nhầm lẫn vì đường này 1 chiều. Đi sai là phải vòng lại tốn rất nhiều thơi gian ',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryID' => 2,
                'name' => 'Sashimi BBQ Garden - Nguyễn Thị Thập',
                'avartar' => 'foody-albumimg_0415-mithalo-jpg-750-635984777177981222.jpg',
                'addressID' => 12,
                'addressDetail' => '2B Nguyễn Thị Thập',
                'phone' => '0984480116',
                'openTime' => '08:30',
                'closeTime' => '21:00',
                'shortDescription' => 'Nhà hàng, Buffet - Món Nhật - Cặp đôi, Gia đình',
                'description' => 'Quán siêu đẹp nhưng hơi khó tìm. Từ Hoàng Minh Giám đi vào NTT 400m thấy ngã tư mà đầu là Chả Cá Lã Vọng thì đi vào tay trái còn đi từ Hoàng Đạo Thuý vào thì thấy quán chả cá rẽ tay phải. ',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryID' => 2,
                'name' => 'Tokyo Yakiniku - Buffet Lẩu Nướng Nhật Bản - Vincom Bà Triệu',
                'avartar' => 'foody-mobile-yaki2-jpg-733-635769603793068903.jpg',
                'addressID' => 13,
                'addressDetail' => 'Tầng 5, Vincom Bà Triệu, 191 Bà Triệu',
                'phone' => '0984480116',
                'openTime' => '08:30',
                'closeTime' => '21:00',
                'shortDescription' => 'Nhà hàng, Buffet - Món Nhật - Cặp đôi, Gia đình',
                'description' => 'Quán siêu đẹp nhưng hơi khó tìm. Từ Hoàng Minh Giám đi vào NTT 400m thấy ngã tư mà đầu là Chả Cá Lã Vọng thì đi vào tay trái còn đi từ Hoàng Đạo Thuý vào thì thấy quán chả cá rẽ tay phải. ',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryID' => 2,
                'name' => 'Family BBQ Buffet - Times City',
                'avartar' => 'foody-mobile-bbq2-jpg-818-635747979453173672.jpg',
                'addressID' => 14,
                'addressDetail' => 'Tầng B1, Time City, 458 Minh Khai',
                'phone' => '0984480116',
                'openTime' => '08:30',
                'closeTime' => '21:00',
                'shortDescription' => 'Nhà hàng, Buffet - Món Nhật, Món Hàn - Gia đình, Nhóm hội',
                'description' => 'Quán siêu đẹp . nằm trong times và có nhiều món ăn để bạn lưạ chọn',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryID' => 2,
                'name' => 'K-Pub - Korean BBQ Garden - Times City',
                'avartar' => 'foody-album21558672_15124853988.jpg',
                'addressID' => 15,
                'addressDetail' => 'B1 Times City, 458 Minh Khai',
                'phone' => '0984480116',
                'openTime' => '08:30',
                'closeTime' => '21:00',
                'shortDescription' => 'Nhà hàng, Buffet - Món Hàn - Sinh viên, Gia đình',
                'description' => 'Vị trí: Kpub nằm ở đường số 9. Gần Thuỷ Cung. Cùng dãy với Kichi rồi Hutong các kiểu luôn vì cùng chuỗi Golden Gate ',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
        ]);
    }
}
